spin_manifest_version = "1"
authors = ["Radu Matei <radu@fermyon.com>"]
name = "my-new-stream-app"
trigger = { type = "http", base = "/" }
version = "0.0.1"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
id = "web"
files = [ { source = "web", destination = "/" } ]
[component.trigger]
route = "/..."

[[component]]
id = "api"
source = "api/target/api.wasm"
ai_models = ["llama2-chat"]
key_value_stores = ["default"]
[component.trigger]
route = "/api/..."
[component.build]
command = "npm run build"
workdir = "api"
watch = ["src/*.ts"]

[[component]]
source = { url = "https://github.com/radu-matei/spin-kv-explorer/releases/download/v0.9.0/spin-kv-explorer.wasm", digest = "sha256:07f5f0b8514c14ae5830af0f21674fd28befee33cd7ca58bc0a68103829f2f9c" }
id = "kv-explorer"
# add or remove stores you want to explore here
key_value_stores = ["default"]
environment = { SPIN_APP_KV_SKIP_AUTH = "1" }
[component.trigger]
route = "/internal/kv-explorer/..."

[[component]]
id = "summary"
source = "summary/target/wasm32-wasi/release/summary.wasm"
allowed_http_hosts = []
ai_models = ["llama2-chat"]
key_value_stores = ["default"]
[component.trigger]
route = "/api/summary/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "summary"
watch = ["src/**/*.rs", "Cargo.toml"]
